// Central business / brand constants
export const SITE = {
  name: "WebDesignFLA",
  brand: "WebDesignFLA",
  tagline: "Website Design, Development & Marketing Agency in Jupiter, FL",
  phoneDisplay: "(561) 464-6222",
  phoneHref: "tel:+15614646222",
  email: "admin@webdesignfla.com",
  addressLine1: "103 South U.S. Hwy 1",
  addressLine2: "Jupiter, FL 33477",
  city: "Jupiter",
  state: "FL",
  zip: "33477",
  url: "https://webdesignfla.com",
  founded: 2010,
  stats: {
    satisfied: 639,
    active: 303,
    statesServed: 48,
    avgYears: 12,
  },
};

export const NAV_LINKS = [
  { label: "Home", to: "/" },
  { label: "Web Design", to: "/web-design/" },
  { label: "SEO", to: "/seo/" },
  { label: "Social Media", to: "/social/" },
  { label: "Portfolio", to: "/portfolio/" },
];

export const PORTFOLIO_ITEMS = [
  { title: "Commercial Building Services", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/commercial.jpg", category: "Web Design" },
  { title: "Stall Savers", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/StallSavers.jpg", category: "Web Design" },
  { title: "Addicted 2 Italy", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/addicted2Itely.jpg", category: "Web Design" },
  { title: "Ariel Homes", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/arielhomes.jpg", category: "Web Design" },
  { title: "Integrity Garage Door Services", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/integrity.jpg", category: "Web Design" },
  { title: "Oceans Treasure", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/OceansTreasure.jpg", category: "Web Design" },
  { title: "Integrated Cable Solutions", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/IntegratedCable.jpg", category: "Web Design" },
  { title: "Smith Fence", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/SmithFence.jpg", category: "Web Design" },
  { title: "Okeefe's Tavern", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/Okeefe.jpg", category: "Web Design" },
  { title: "Florida Tech Law", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/floridatechlaw.jpg", category: "Web Design" },
  { title: "Clear-Tech Pools", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/ClearTech.jpg", category: "Web Design" },
  { title: "Childcare Of Brandon", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/childcareofbrandon.jpg", category: "Web Design" },
  { title: "Inject-A-Deck", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/injectadeck.jpg", category: "Web Design" },
  { title: "Trident H2O", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/skywaterpools.jpg", category: "Web Design" },
  { title: "Upper Room", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/upperroom.jpg", category: "Web Design" },
  { title: "Oasis Climatic", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/oasis.jpg", category: "Web Design" },
  { title: "Superior Auto Loans", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/superiorauto.jpg", category: "Web Design" },
  { title: "Mickey's Peanuts", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/mickeyspeanuts.jpg", category: "Web Design" },
  { title: "JetBrite", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/jetbrite.jpg", category: "Web Design" },
  { title: "How The Mind Works", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/howthemindworks.jpg", category: "Web Design" },
  { title: "Florida Covered Storage", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/floridacoveredstorage.jpg", category: "Web Design" },
  { title: "Michael's Pool Service", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/michaelspool.jpg", category: "Web Design" },
  { title: "Dynatherm", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/dynatherm.jpg", category: "Web Design" },
  { title: "Compass Limo", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/compasslimo.jpg", category: "Web Design" },
  { title: "Clearwater Tub And Tile Refinishing", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/clearwatertub.jpg", category: "Web Design" },
  { title: "Backyard Pool Service", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/backyardpool.jpg", category: "Web Design" },
  { title: "7 Springs Self Storage", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/7springs.jpg", category: "Web Design" },
  { title: "Upperroom Recording", img: "https://www.webdesignfla.com/wp-content/uploads/2020/01/upperroomrecording.jpg", category: "Web Design" },
];
